### ISSUE TITLE
code sharing

### ISSUE THREAD

**Issue by gmt710** [nesl/adversarial_genattack#1]
I look forward to your code sharing.

**Comment by iwhalen** [comment]
@malzantot any update on this code?

**Comment by malzantot** [comment]
@ianwhale  : the repo will be updated and code will be released within the upcoming two weeks (first half of Nov).

**Comment by maxidl** [comment]
@malzantot any update on this? I would like to try using your approach for a university project of mine, which will be due soon. Thanks in advance!

**Comment by hassanali-khatim** [comment]
@malzantot Any update on this?

**Comment by malzantot** [comment]
Hi everyone, we are sorry for the delay which is out of our hands due to being busy on other projects as well as on preparing a newer version of the paper. Preparing the code for public release would take us a few bit of time to make it easy for everyone to run and use. Please expect an update within the upcoming two weeks.
Thanks for your understanding.

**Comment by malzantot** [comment]
Hi everyone, Sorry for the delay on our side due to being busy with a lot of projects. The repo is updated now with the code . The version in the code have more improvements than the algorithm described in our previous version of the paper, and the updated paper will also be released soon. Thanks!
